name: Lint, Format & Test

on: [push, pull_request]

permissions:
    contents: write
    checks: write
    pull-requests: write

jobs:
    Quality:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install black pylint isort mypy
                  python -m pip install types-PyYAML

            - name: Set PYTHONPATH
              run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

            - name: Run Black
              run: black --check $(git ls-files '*.py')

            - name: Run Pylint
              run: pylint $(git ls-files '*.py')

            - name: Run Isort
              run: isort --check-only $(git ls-files '*.py')

    Tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest pytest-cov

            - name: Set PYTHONPATH
              run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

            - name: Run tests and coverage
              run: |
                  pytest --cov=$(pwd) tests/

            - name: Upload coverage data
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-data
                  path: .coverage
                  if-no-files-found: ignore

    Coverage:
        name: Coverage
        needs: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade coverage[toml]

            - name: Download coverage data
              uses: actions/download-artifact@v4
              with:
                  name: coverage-data

            - name: Combine coverage
              run: |
                  coverage html --skip-covered --skip-empty
                  coverage_report=$(coverage report)
                  echo "$coverage_report" | sed 's/^/    /' >> $GITHUB_STEP_SUMMARY
                  total_coverage=$(echo "$coverage_report" | grep 'TOTAL' | awk '{print $4}' | sed 's/%//')
                  echo "TOTAL=${total_coverage}" >> $GITHUB_ENV

            - name: Sanitize branch name
              id: sanitize_branch
              run: |
                  sanitized_branch_name="${GITHUB_REF#refs/heads/}"
                  sanitized_branch_name="${sanitized_branch_name//\//_}"
                  echo "SANITIZED_BRANCH_NAME=${sanitized_branch_name}" >> $GITHUB_ENV

            - name: Extract repository name
              id: extract_repo
              run: |
                  repo_name="${GITHUB_REPOSITORY#*/}"
                  echo "REPO_NAME=${repo_name}" >> $GITHUB_ENV

            - name: Create badge
              uses: schneegans/dynamic-badges-action@v1.7.0
              with:
                  auth: ${{ secrets.GIST_TOKEN }}
                  gistID: bfba49c1003e973932c4de7dcc3e969a
                  filename: ${{ env.REPO_NAME }}_${{ env.SANITIZED_BRANCH_NAME }}.txt
                  label: Coverage
                  message: ${{ env.TOTAL }}%
                  minColorRange: 50
                  maxColorRange: 90
                  valColorRange: ${{ env.TOTAL }}
                  forceUpdate: true

            - name: Generate badge URL
              run: |
                  badge_url="https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/AdrienSpecht/bfba49c1003e973932c4de7dcc3e969a/raw/${{ env.REPO_NAME }}_${{ env.SANITIZED_BRANCH_NAME }}.txt"
                  echo "BADGE_URL=${badge_url}" >> $GITHUB_ENV

            - name: Check if README needs update
              run: |
                  if grep -q "![Coverage](${{ env.BADGE_URL }})" README.md; then
                    echo "README is up to date."
                    echo "README_NEEDS_UPDATE=false" >> $GITHUB_ENV
                  else
                    echo "README needs update."
                    echo "README_NEEDS_UPDATE=true" >> $GITHUB_ENV
                    if grep -q "![Coverage](https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/AdrienSpecht/bfba49c1003e973932c4de7dcc3e969a/raw/*.txt)" README.md; then
                      echo "Coverage badge absent in README"
                    else
                      echo "Coverage badge present in README"
                    fi
                  fi
              shell: bash

            - name: Update README with badge URL
              if: env.README_NEEDS_UPDATE == 'true'
              run: |
                  echo "Replacing coverage badge URL in README.md"
                  sed -i "s|![Coverage](https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/AdrienSpecht/bfba49c1003e973932c4de7dcc3e969a/raw/*.txt)|![Coverage](${{ env.BADGE_URL }})|" README.md
                  echo "Updated README:"
                  cat README.md

            - name: Commit updated README
              if: env.README_NEEDS_UPDATE == 'true'
              run: |
                  git config --global user.name 'github-actions'
                  git config --global user.email 'github-actions@github.com'
                  git add README.md
                  git commit -m "Update coverage badge URL"
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
