name: Checks

on: [push, pull_request]

permissions:
    contents: write
    checks: write
    pull-requests: write

jobs:
    quality:
        runs-on: ubuntu-latest

        steps:
            - name: Print Directory Structure at the start
              run: ls -R $GITHUB_WORKSPACE

            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Print GITHUB_WORKSPACE after checkout
              run: |
                  echo "GITHUB_WORKSPACE after checkout: $GITHUB_WORKSPACE"

            - name: Print Directory Structure after checkout
              run: ls -R $GITHUB_WORKSPACE
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Print Directory Structure before everything
              run: ls -R $GITHUB_WORKSPACE

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install black pylint isort mypy
                  python -m pip install types-PyYAML

            - name: Print Directory Structure before
              run: ls -R $GITHUB_WORKSPACE

            - name: Set PYTHONPATH
              run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

            - name: Print Directory Structure after
              run: ls -R $GITHUB_WORKSPACE

            - name: Run Black
              run: black --check $(git ls-files '*.py')

            - name: Run Pylint
              run: pylint $(git ls-files '*.py')

            - name: Run Isort
              run: isort --check-only $(git ls-files '*.py')

            - name: Run Mypy
              run: mypy $(git ls-files '*.py')

    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest pytest-cov

            - name: Set PYTHONPATH
              run: echo "PYTHONPATH=$GITHUB_WORKSPACE/proteomics" >> $GITHUB_ENV

            - name: Verify PYTHONPATH
              run: echo ${{ env.PYTHONPATH }}

            - name: Run Tests
              run: |
                  if ls tests/*.py 1> /dev/null 2>&1; then
                      pytest tests/*.py
                  else
                      echo "No test files found"
                  fi

            - name: Upload coverage data
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-data
                  path: .coverage.*
                  if-no-files-found: ignore

    coverage:
        name: Combine and check coverage
        needs: tests
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade coverage[toml]

            - name: Download coverage data
              uses: actions/download-artifact@v4
              with:
                  name: coverage-data

            - name: Combine coverage and fail it it’s under 20 %
              run: |
                  python -m coverage combine
                  python -m coverage html --skip-covered --skip-empty

                  # Report and write to summary.
                  python -m coverage report | sed 's/^/    /' >> $GITHUB_STEP_SUMMARY

                  # Report again and fail if under 20%.
                  python -Im coverage report --fail-under=20

            - name: Upload HTML report if check failed
              uses: actions/upload-artifact@v4
              with:
                  name: html-report
                  path: htmlcov
              if: ${{ failure() }}

            - name: Create badge
              uses: schneegans/dynamic-badges-action@v1.7.0
              with:
                  auth: ${{ secrets.GIST_TOKEN }}
                  gistID: 94f9182f0a9c3c48c35477c65f056c4d
                  filename: covbadge.json
                  label: Coverage
                  message: ${{ env.total }}%
                  minColorRange: 50
                  maxColorRange: 90
                  valColorRange: ${{ env.total }}
