name: Checks

on: [push, pull_request]

jobs:
    checks:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install black pylint isort mypy pytest
                  python -m pip install types-PyYAML

            - name: Run Black
              run: black --check .

            - name: Run Pylint
              run: pylint **/*.py

            - name: Run Isort
              run: isort --check-only .

            - name: Run Mypy
              run: mypy .

            - name: Run Tests
              run: |
                  if ls tests/*.py 1> /dev/null 2>&1; then
                      pytest
                  else
                      echo "No test files found"
                  fi


